# Generated by Django 2.1.7 on 2019-03-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='file',
            field=models.ImageField(default='', upload_to='', verbose_name='graffiti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='heartless', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_point',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='character',
            name='magic_point',
            field=models.IntegerField(default=1000),
        ),
    ]
