# Generated by Django 2.1.7 on 2019-03-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190330_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='file',
            new_name='graffiti_image',
        ),
    ]
