# Generated by Django 2.1.7 on 2019-03-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190330_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='graffiti_image',
            field=models.ImageField(upload_to='uploads/graffiti/', verbose_name='graffiti'),
        ),
    ]
