# Generated by Django 2.1.7 on 2019-03-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190330_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='defence',
            new_name='attack_point',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='luck',
            new_name='defence_point',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='power',
            new_name='luck_point',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='speed',
            new_name='speed_point',
        ),
    ]
