# Generated by Django 2.1.7 on 2019-04-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190331_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userandcharacterlink',
            old_name='character_id',
            new_name='character_key',
        ),
        migrations.RenameField(
            model_name='userandcharacterlink',
            old_name='user_id',
            new_name='user_key',
        ),
    ]
